### ISSUE TITLE
Couln't find metadata for "new variables"

### ISSUE THREAD

**Issue by chenfsu** [MITgcm/xmitgcm#173]
I encountered an issue in Xmitgcm. I have used it to read variables from standard MITgcm outputs, such as U V and T. But now I am running MITgcm with a new module (cheapAML, a simply atmospheric boundary layer model), and it added a few new variables to it. the Xmitgcm now can't recognize the new variables and return the error info as below.

Would you give me some hit on how to fix this issue? Thanks!

/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py:837: UserWarning: Couldn't find available_diagnostics.log in /gpfs/research/coaps/home/xc11/zStudent_s2014e2018/61_mitgcm_201904/MITgcm/verification/02_gom_cheapAML/01_zdata_20130507_040_04ENoCurrent/diag_snap or /gpfs/research/coaps/home/xc11/zStudent_s2014e2018/61_mitgcm_201904/MITgcm/verification/02_gom_cheapAML/01_zdata_20130507_040_04ENoCurrent/diag_snap. Using default version.
  "in %s or %s. Using default version." % (data_dir, grid_dir))
Traceback (most recent call last):
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 168, in open_mdsdataset
    iternum = int(iters)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 630, in load_from_prefix
    else self._all_data_variables[vname])
KeyError: 'CH_TAIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "01000_Temp_01040.py", line 14, in <module>
    ds=open_mdsdataset(data_dir)
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 206, in open_mdsdataset
    for iternum in iters]
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 206, in <listcomp>
    for iternum in iters]
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 230, in open_mdsdataset
    extra_metadata=extra_metadata)
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 527, in __init__
    self.load_from_prefix(p, iternum, extra_metadata):
  File "/gpfs/home/xc11/.conda/envs/test/lib/python3.7/site-packages/xmitgcm/mds_store.py", line 638, in load_from_prefix
    "and `ignore_unknown_vars`==False." % vname)
KeyError: "Couln't find metadata for variable CH_TAIR and `ignore_unknown_vars`==False."

**Comment by timothyas** [comment]
Hey @chenfsu, it looks like the directory where your data live doesn't have the `available_diagnostics.log` file and so xmitgcm is doing its best by using a default that it has, which likely doesn't have the cheapaml diagnostic variables. If you copy that log file to wherever your output is do you still get the same error?

**Comment by rabernat** [comment]
@timothyas said exactly what I would have said.

**Comment by chenfsu** [comment]
Thanks, Tim and Ryan @timothyas @rabernat. Yes, it works well now after I put the available_diagnostics.log file into the data directory.
