### ISSUE TITLE
When calling xmitgcm.llcreader.faces_dataset_to_latlon (ds, metric_vector_pairs = ['dxC','dyC','dyG','dxG']), an error is reported

### ISSUE THREAD

**Issue by csy0101** [MITgcm/xmitgcm#218]
from xmitgcm import open_mdsdataset
import xmitgcm
from xmitgcm import llcreader
data_dir = 'L:\global_oce_latlon'
ds = open_mdsdataset(data_dir, prefix='Eta')
xmitgcm.llcreader.faces_dataset_to_latlon(ds, metric_vector_pairs=['dxC', 'dyC','dyG', 'dxG'])
eta = ds.Eta
a = eta.values[0,:,:]
# a[a==0] = np.NaN
print(a)
AttributeError                            Traceback (most recent call last)
<ipython-input-70-9af8a7c66513> in <module>
      6 # display the contents of the Dataset
      7 # prefix = ["Eta"]
----> 8 xmitgcm.llcreader.faces_dataset_to_latlon(ds, metric_vector_pairs=['dxC', 'dyC','dyG', 'dxG'])
      9 eta = ds.Eta
     10 a = eta.values[0,:,:]

AttributeError: module 'xmitgcm.llcreader' has no attribute 'faces_dataset_to_latlon'

**Comment by rabernat** [comment]
Hi @csy0101, thanks for your issue. We'd like to help, but I'm afraid I'm not sure exactly what you are asking. Could you please describe what you are trying to accomplish?

**Comment by csy0101** [comment]
> 嗨@ csy0101，谢谢您的问题。我们想提供帮助，但是恐怕我不确定您要问的是什么。您能否描述您要完成的工作？


I extracted the eta data from the output data of llc4320,but the coordinates are in LLC coordinates, I want eta data in latitude and longitude coordinates.The llcreader module also has a standalone function for converting 13-face-style LLC datasets into rectangular quasi-lat-lon datasets.  'xmitgcm.llcreader.faces_dataset_to_latlon(ds, metric_vector_pairs=['dxC', 'dyC', 'dyG', 'dxG'])' ,
I want to use this function to convert it.The above error occurred...Thank  you!

**Comment by csy0101** [comment]
9 eta = ds.Eta
10 a = eta.values[0,:,:]
These two lines of commands are I want to save them as a separate array,has nothing to do with coordinate conversion

**Comment by csy0101** [comment]
> 嗨@ csy0101，谢谢您的问题。我们想提供帮助，但是恐怕我不确定您要问的是什么。您能否描述您要完成的工作？

In addition, I would like to ask how the 13 interviews of llc4320 are distributed. If possible, what is the range of latitude and longitude of each face? Or where do I get the information? Thank you

**Comment by csy0101** [comment]
> 嗨@ csy0101，谢谢您的问题。我们想提供帮助，但是恐怕我不确定您要问的是什么。您能否描述您要完成的工作？

thank you for your reply! I extracted the eta file in the output file of llc4320, which is what I want. I learned from LLCreader that the llcreader module also has a standalone function for converting 13-face-style LLC datasets into rectangular quasi-lat-lon datasets.
The function is“xmitgcm.llcreader.faces_dataset_to_latlon(ds, metric_vector_pairs=['dxC', 'dyC', 'dyG', 'dxG'])”，I want to implement this function ，convert the LLC data set to a quasi-quasi-rectangular data set.The following error occurred
'''
Traceback (most recent call last):
  File "I:\MITgcmLLC4320\test.py", line 17, in <module>
    dslatlon = lm.faces_dataset_to_latlon(ds,metric_vector_pairs=[('dxC', 'dyC'), ('dyG', 'dxG')])
  File "C:\Users\Admin\anaconda3\lib\site-packages\xmitgcm\llcreader\llcmodel.py", line 291, in faces_dataset_to_latlon
    data_u, data_v = _faces_to_latlon_vector(ds[vname_u].data, ds[vname_v].data, metric=True)
  File "C:\Users\Admin\anaconda3\lib\site-packages\xmitgcm\llcreader\llcmodel.py", line 202, in _faces_to_latlon_vector
    u_facets = _faces_to_facets(u_faces)
  File "C:\Users\Admin\anaconda3\lib\site-packages\xmitgcm\llcreader\llcmodel.py", line 126, in _faces_to_facets
    assert data.shape[facedim] == _nfaces
IndexError: tuple index out of range'''

**Comment by csy0101** [comment]
> 嗨@ csy0101，谢谢您的问题。我们想提供帮助，但是恐怕我不确定您要问的是什么。您能否描述您要完成的工作？

This is my code 
'''from xmitgcm import open_mdsdataset
import xarray as xr
import scipy
import numpy
import xmitgcm.llcreader.llcmodel as lm

# data_dir = 'C:\\Users\\12031\\Desktop\\11'
data_dir = 'L:\\2011.09.13'
grid_dir = 'N:\\llc4320\\grid'
# data_dir = 'L:\\global_oce_latlon'
prefix = ["Eta"]
ds = open_mdsdataset(data_dir, grid_dir, iters='all', prefix=prefix, read_grid=True, delta_t=1, ref_date=None, calendar='gregorian', geometry='sphericalpolar', grid_vars_to_coords=True, swap_dims=None, endian='>', chunks=None, ignore_unknown_vars=False, default_dtype=None, nx=None, ny=None, nz=None, llc_method='smallchunks', extra_metadata=None)
print(ds)
YClon = ds.YC.values
XClat = ds.XC.values

dslatlon = lm.faces_dataset_to_latlon(ds,metric_vector_pairs=[('dxC', 'dyC'), ('dyG', 'dxG')])
# ds.to_netcdf('eta.nc')
# eta = ds.Eta
# eta = ds.Eta
# a = eta.values[0,:,:]
# print(a)
# numpy.savetxt("YClon.txt",YClon,fmt='%f',delimiter=',')
# numpy.savetxt("XClat.txt",XClat,fmt='%f',delimiter=',')
# fig = plt.figure()
# ax = Axes3D(fig)
'''

**Comment by csy0101** [comment]
> Hi @csy0101, thanks for your issue. We'd like to help, but I'm afraid I'm not sure exactly what you are asking. Could you please describe what you are trying to accomplish?

This is my code'''from xmitgcm import open_mdsdataset
import xarray as xr
import scipy
import numpy
import xmitgcm.llcreader.llcmodel as lm

# data_dir = 'C:\\Users\\12031\\Desktop\\11'
data_dir = 'L:\\2011.09.13'
grid_dir = 'N:\\llc4320\\grid'
# data_dir = 'L:\\global_oce_latlon'
prefix = ["Eta"]
ds = open_mdsdataset(data_dir, grid_dir, iters='all', prefix=prefix, read_grid=True, delta_t=1, ref_date=None, calendar='gregorian', geometry='sphericalpolar', grid_vars_to_coords=True, swap_dims=None, endian='>', chunks=None, ignore_unknown_vars=False, default_dtype=None, nx=None, ny=None, nz=None, llc_method='smallchunks', extra_metadata=None)
print(ds)
YClon = ds.YC.values
XClat = ds.XC.values

dslatlon = lm.faces_dataset_to_latlon(ds,metric_vector_pairs=[('dxC', 'dyC'), ('dyG', 'dxG')]) '''

**Comment by csy0101** [comment]
> Hi @csy0101, thanks for your issue. We'd like to help, but I'm afraid I'm not sure exactly what you are asking. Could you please describe what you are trying to accomplish?

this is my code 
‘’‘from xmitgcm import open_mdsdataset
import xarray as xr
import scipy
import numpy
import xmitgcm.llcreader.llcmodel as lm
data_dir = 'L:\\2011.09.13'
grid_dir = 'N:\\llc4320\\grid'
prefix = ["Eta"]
ds = open_mdsdataset(data_dir, grid_dir, iters='all', prefix=prefix, read_grid=True, delta_t=1, ref_date=None, calendar='gregorian', geometry='sphericalpolar', grid_vars_to_coords=True, swap_dims=None, endian='>', chunks=None, ignore_unknown_vars=False, default_dtype=None, nx=None, ny=None, nz=None, llc_method='smallchunks', extra_metadata=None)
print(ds)
YClon = ds.YC.values
XClat = ds.XC.values
dslatlon = lm.faces_dataset_to_latlon(ds,metric_vector_pairs=[('dxC', 'dyC'), ('dyG', 'dxG')])

**Comment by dhruvbalwada** [comment]
Hi @csy0101 - I tried to reproduce the problem, but was unable to do so. Here is how I read in the data and converted to latlon: 

<img width="714" alt="Screen Shot 2020-09-08 at 9 48 43 PM" src="https://user-images.githubusercontent.com/18236610/92555730-2b246400-f21d-11ea-8760-107dc5b4fc1d.png">
(I am using the google cloud, so the cat_4320 is just the catalogue where there data is stored (https://catalog.pangeo.io/browse/master/ocean/LLC4320/)

Not sure why it is not working for you, are you sure your grid variables are being read in correctly? If something like what I posted doesn't work for you, then can you actually post what you 'ds' look like?

**Comment by csy0101** [comment]
> @ csy0101，您好-我尝试重现此问题，但无法做到这一点。这是我读取数据并转换为latlon的方法：
> 
> <img alt="截屏2020-09-08,9 48 43 PM" width="714" src="https://user-images.githubusercontent.com/18236610/92555730-2b246400-f21d-11ea-8760-107dc5b4fc1d.png">
> 
> （我使用的是Google云，因此cat_4320只是存储数据的目录（https://catalog.pangeo.io/browse/master/ocean/LLC4320/）
> 不知道为什么它对您不起作用，您确定正确读取了网格变量吗？如果像我发布的内容对您不起作用，那么您可以实际发布“ ds”的外观吗？

Thank you for your reply. I downloaded all the grid data released by ECCO.For eta, perform the following operations to achieve coordinate conversion.
’‘’dslatlon = lm.faces_dataset_to_latlon（ds，metric_vector_pairs = [ ]）‘’‘
But this is not applicable to U and V data, I will continue to try. Do you have any explanations for this?

**Comment by dhruvbalwada** [comment]
I am not sure I am completely understanding the problem. Try to follow the protocol explained here: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports : when reporting issues. 

<img width="961" alt="Screen Shot 2020-09-09 at 9 15 55 AM" src="https://user-images.githubusercontent.com/18236610/92625064-1677b880-f27d-11ea-907d-0f0b7ff72ed9.png">
The only thing I can guess is that maybe you are trying to convert just u or v individually, but you need to pass them together. See in the above example that you need an xarray with u and v together for the `faces_dataset_to_latlon` to work.

**Comment by csy0101** [comment]
> 我不确定我是否完全理解这个问题。尝试遵循此处说明的协议：[http](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) : [//matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)：报告问题时。
> 
> <img alt="截屏2020-09-09 at 9 15 55 AM" width="961" src="https://user-images.githubusercontent.com/18236610/92625064-1677b880-f27d-11ea-907d-0f0b7ff72ed9.png">
> 
> 我唯一能猜到的是，也许您只是尝试分别转换u或v，但是您需要将它们一起传递。在上面的示例中，您需要一个同时包含u和v的xarray来使faces_dataset_to_latlon工作。

Yes, my original plan was to convert U and V separately. Now I will try your suggestion and change together.

**Comment by csy0101** [comment]
> 我不确定我是否完全理解这个问题。尝试遵循此处说明的协议：[http](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) : [//matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)：报告问题时。
> 
> <img alt="截屏2020-09-09 at 9 15 55 AM" width="961" src="https://user-images.githubusercontent.com/18236610/92625064-1677b880-f27d-11ea-907d-0f0b7ff72ed9.png">
> 
> 我唯一能猜到的是，也许您只是尝试分别转换u或v，但是您需要将它们一起传递。在上面的示例中，您需要一个同时包含u和v的xarray来使faces_dataset_to_latlon工作。


Thanks for your suggestion, I have resolved this issue.
